// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smeenikrmaomktodybzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZWVuaWtybWFvbWt0b2R5YnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjQ1NTUsImV4cCI6MjA3MzM0MDU1NX0.hRh9ZKN6CHZtYbpcFCFlhWA1DEZMOX0keGh4vIz-Ghc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});